### ISSUE TITLE
[EPIC] Create permission system to access SDK methods

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-apps-sdk#318]
## Overview
After discussing this problem statement https://github.com/safe-global/safe-pm/issues/98 it was decided that a permission system could be a good approach to let users to access rich features when interacting with third party apps. Many users requested that they could for example use the addressbook in Safe Apps, but as this would involve sharing personal information with an external provider information shouldn't be accessible by default

## Requirements

- [ ] Create a way of requesting permissions need from Safe Apps
- [ ] Create a RPC style SDK method to get addressbook information
- [ ] Add a permission check on the SDK allowing or disallowing to use certain RPC methods. Would be interesting to check [Metamask permission proposal](https://docs.metamask.io/guide/rpc-api.html#restricted-methods)
- [ ] Store configuration regarding user permissions so we remember user options when they come back
- [ ] Create a management section in settings
- [ ] Add a button to manage Safe Apps permisions redirecting from Safe Apps list
