### ISSUE TITLE
[Epic] Outdated documentation and missing example material to onboard devs

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-apps-sdk#355]
## Overview
This epic will be focused into updating docs and example material to use Safe Apps SDK. Developers have troubles following current documentation and we are missing strong examples to showcase the possibilities of integrating with the Safe.

Roadmap Epic:
https://www.notion.so/gnosis-safe/Safe-App-SDK-Improving-documentation-and-example-material-ef918763b2854b9e8977658d88081230

## Goals
 - Create an example Safe App that could be used as step by step tutorial guide
 - Update `safe-apps-sdk` readmes
 - Update all help docs related to Safe Apps and Safe Apps SDK

## Requirements
- [ ] Example Safe App showing how to integrate existing projects using onboard.js
- [ ] Example Safe App showing direct integration usign the SDK
- [ ] Create small faucet to give out testing tokens so participants can create a new Safe on a cheap chain or testnet if needed
- [ ] Update help documents
- [ ] Update gitbook developer pages
- [ ] Create slideshow to guide example in public
- [ ] Update testing/QA app as am example Safe App
- [ ] Add more information to CRA template docs
