### ISSUE TITLE
[Epic] Extract communicator logic from the web

### ISSUE THREAD

**Issue by dasanra** [safe-global/safe-apps-sdk#380]
## Overview
We will extract the communicator logic to a separate package so it's easier to implement Safe Apps integration in other interfaces, so its code can be reused. Once we extract it to a separate library we will publish as a package that the web interface will use.

Roadmap Epic:
https://www.notion.so/gnosis-safe/Extract-communicator-logic-from-the-web-app-61be146f10774eb5ae89f3f7e375c453

Notes about refactoring
https://www.notion.so/gnosis-safe/AppFrame-refactoring-aec86f7ce0fd49b18f9a621e7f22d5ff

## Requirements
- [ ] Separate communicator logic to an isolated component in the web interface
- [ ] Move this code to a separated repository
- [ ] Publish an npm package that can be used later
- [ ] Separate event subscription logic on the web side so there are less dependencies in the hook
- [ ] Review if is possible to decouple the AppComunicator from the iFrame. Currently we need to pass the iFrame to the AppComunicator instance. Maybe it shouldn't be necesary to do it like this
